# Generated by Django 5.2 on 2025-06-16 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_movimientoinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='tasks.iteminventario')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'unique_together': {('item', 'numero_lote')},
            },
        ),
    ]
