# Generated by Django 5.2 on 2025-06-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='items', to='tasks.categoria'),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='items', to='tasks.etiqueta'),
        ),
    ]
