# Generated by Django 5.2 on 2025-06-17 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_historialprecio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('componentes_kits', models.ManyToManyField(blank=True, related_name='parent_kits', to='tasks.kit')),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
            },
        ),
        migrations.CreateModel(
            name='KitComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.iteminventario')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.kit')),
            ],
            options={
                'verbose_name': 'Componente de Kit',
                'verbose_name_plural': 'Componentes de Kits',
                'unique_together': {('kit', 'item')},
            },
        ),
        migrations.AddField(
            model_name='kit',
            name='componentes_items',
            field=models.ManyToManyField(related_name='kits', through='tasks.KitComponente', to='tasks.iteminventario'),
        ),
    ]
